<script>
	import chroma from "chroma-js"
	import { getContext, onMount } from "svelte"
	import * as THREE from "three"
	
	export let colorScale
	export let currentActivePollutant
	export let currentYear
	let pollutantGraphicElement
	
	$: activePollutant = currentActivePollutant ? currentActivePollutant : activePollutant
	
	let store = getContext("store")
	
	const pollutantTexts = {
		"BC": [
			"Major outdoor sources of black carbon exposure are traffic and occasionally forest fires. Despite the fact that a large portion of the exposure occurs as short peaks of high concentrations, it is unclear how to define peaks and determine their frequency and health impact.",  
			"High in-vehicle concentrations of black carbon have been associated with driving during rush hours, on highways and in dense traffic. Even relatively low exposure concentrations of Black Carbon have a direct effect on the lung function of adults and an inflammatory effect on the respiratory system of children. By reducing black carbon, a primary component of fine particulate matter, the health risks from air pollution will decline. In fact, public health concerns have given rise to leading to many efforts to reduce such emissions, for example, from diesel vehicles and cooking stoves."
		],
		
		"CO": [
			"Carbon monoxide is formed during the incomplete combustion of combustibles and fuels. It forms when too little oxygen is available during combustion processes. In higher concentrations, CO acts as a powerful respiratory poison. The main source of CO pollution in the air is motor vehicle traffic.",
			"As an air pollutant, carbon monoxide impairs oxygen uptake by humans and animals. CO is a potent respiratory poison and can also have effects on the central nervous system."
		],
		
		"NH3": [
			"With a share of around 95 percent, agriculture is the main emitter of the air pollutant ammonia in Germany. Other emitters are industry, the energy sector and waste management. Ammonia escapes mainly from farmyard manure and slurry, which are produced when livestock are kept indoors, stored and spread on agricultural land. Other sources of ammonia include the application of mineral N fertilizers and digestate from biogas production and, to a lesser extent, excreta from grazing animals.",
			
			"Ammonia disperses in the atmosphere, is transported, and is deposited in ecosystems, where it can then lead to unwanted and uncontrollable eutrophication effects. In addition, atmospheric ammonia deposition also contributes to soil acidification. However, ammonia also directly damages ecosystems and plants by acting toxically through leaf organs. Species that are particularly sensitive are lichens, but higher plants in nutrient-poor heath and grassland ecosystems and ground vegetation in forests are also sensitive to ammonia. Ammonia can thus lead to changes in the species composition of biotic communities and to the death of individual species."
			],
		
		"NMVOC": ["Volatile organic compounds (VOCs) comprise a large number of substances whose molecular structure is based on a carbon skeleton. They can have a wide variety of effects on the environment, for example on a large scale through the formation of photooxidants, locally as odor nuisance or even as carcinogenic substances (for example benzene). Therefore, the impact potential cannot be concluded from the total emission alone. However, the total amount of emissions is important with regard to the role of VOCs as precursors of secondary air pollutants: together with nitrogen oxides, they lead to the formation of ground-level ozone, for example \"summer smog\"."],
		
		"NOx": [
			"Nitrogen oxides are produced during combustion processes. The main sources of nitrogen oxides in outdoor air are combustion engines and furnaces (for coal, oil, gas, wood, waste). In urban areas, road traffic is the most significant source of nitrogen oxides, with the largest share coming from diesel engines in passenger cars, light and heavy commercial vehicles, and diesel-powered buses.", 
			
			"First of all, nitrogen dioxide (NO2) as such is an irritant gas and acts as a very reactive compound (oxidant) especially on the lower respiratory tract. There, depending on the strength and duration of exposure, damage occurs to the lung cells. The irritant effect and the associated oxidative stress also result in inflammatory processes, which can also have damaging effects in other organs. A large number of epidemiological studies are now available that have shown associations with a variety of diseases of the lung and cardiovascular system (for example, asthma, heart attacks, and strokes)."
		],
		
		"PM10": [
			"Particulate matter is primarily generated by human activity: Primary particulate matter is generated by emissions from motor vehicles, power and district heating plants, furnaces and heaters in residential buildings, metal and steel production, or the handling of bulk materials. It can also be of natural origin (for example, as a result of soil erosion). In urban areas, road traffic is the dominant source of dust. Fine dust enters the air not only from engines - primarily diesel engines - but also from brake and tire abrasion and from dust being stirred up from the road surface.",
			
			"In humans, PM10 can penetrate the nasal cavity, PM2.5 can penetrate as far as the bronchi and alveoli, and ultrafine particles can penetrate as far as the lung tissue and even the bloodstream. Depending on the size and penetration depth of the particles, the health effects of particulate matter vary. They range from mucosal irritation and local inflammation in the trachea and bronchi or pulmonary alveoli to increased plaque formation in the blood vessels, an increased tendency to thrombosis, or changes in the regulatory function of the autonomic nervous system (heart rate variability)."
		],
		
		"PM2.5": [
			"Particulate matter is primarily generated by human activity: Primary particulate matter is generated by emissions from motor vehicles, power and district heating plants, furnaces and heaters in residential buildings, metal and steel production, or the handling of bulk materials. It can also be of natural origin (for example, as a result of soil erosion). In urban areas, road traffic is the dominant source of dust. Fine dust enters the air not only from engines - primarily diesel engines - but also from brake and tire abrasion and from dust being stirred up from the road surface.",
			
			"In humans, PM10 can penetrate the nasal cavity, PM2.5 can penetrate as far as the bronchi and alveoli, and ultrafine particles can penetrate as far as the lung tissue and even the bloodstream. Depending on the size and penetration depth of the particles, the health effects of particulate matter vary. They range from mucosal irritation and local inflammation in the trachea and bronchi or pulmonary alveoli to increased plaque formation in the blood vessels, an increased tendency to thrombosis, or changes in the regulatory function of the autonomic nervous system (heart rate variability)."
		],
		
		"SO2": [
			"Sulfur dioxide that affects humans and the environment. Sulfate particles formed in the atmosphere from sulfur dioxide also contribute to particulate matter (PM10) pollution. Sulfur dioxide is mainly produced during combustion processes of fossil fuels such as coal and oil by oxidation of the sulfur contained in the fuel.",
			
			"Sulfur dioxide irritates mucous membranes and can cause eye irritation and respiratory problems. Since SO2 concentrations nationwide are very significantly below the applicable limits for the protection of human health, health problems caused by SO2 are no longer a concern in Germany today."
		],
		
		"TSP": [
			"Total Suspended Particles is the fraction sampled with high-volume samplers, approximately particle diameters less than 50–100 µm.",
			"Major sources of primary particles are industrial processes, road traffic, power plants, domestic burning (coal, wood, etc.), incineration, and resuspension of road and construction dust. Particulate matter is removed from the atmosphere by wet and dry deposition.",
			
		]
		
	}
	
	const pollutantTitles = {
		"BC": "Black carbon",
		"CO": "Carbon Monoxide",
		"NH3": "Ammonia",
		"NMVOC": "Non-methane volatile organic compound",
		"NOx": "Nitrogen Oxides",
		"PM10": "Particle Matter < 10 µm",
		"PM2.5": "Particle Matter < 2.5 µm",
		"SO2": "Sulfur dioxide",
		"TSP": "Total Suspended Particles"
	}
	
	const pollutantTextSources = {
		"BC": "https://en.wikipedia.org/wiki/Black_carbon",
		"CO": "https://www.umweltbundesamt.de/themen/luft/luftschadstoffe-im-ueberblick/kohlenmonoxid",
		"NH3": "https://www.umweltbundesamt.de/themen/luft/luftschadstoffe-im-ueberblick/ammoniak#rechtliche-grundlagen",
		"NMVOC": "https://www.umweltbundesamt.de/daten/luft/luftschadstoff-emissionen-in-deutschland/emission-fluechtiger-organischer-verbindungen-ohne#-erfullungsstand-von-minderungsbeschlussen",
		"NOx": "https://www.umweltbundesamt.de/themen/luft/luftschadstoffe-im-ueberblick/stickstoffoxide/stickstoffdioxid-gesundheitliche-bedeutung-von#warum-betrachtet-man-insbesondere-stickstoffdioxid",
		"PM10": "https://www.umweltbundesamt.de/themen/luft/luftschadstoffe-im-ueberblick/feinstaub",
		"PM2.5": "https://www.umweltbundesamt.de/themen/luft/luftschadstoffe-im-ueberblick/feinstaub",
		"SO2": "https://www.umweltbundesamt.de/themen/luft/luftschadstoffe-im-ueberblick/schwefeldioxid",
		"TSP": "https://www.eea.europa.eu/publications/2-9167-057-X/page021.html"
	}
	
	let size = {
		h: 0,
		w: 0
	}
	
	const scene = new THREE.Scene();

	
	
	let mesh = null
	
	let cubeGeometry = () => {
		
		if(!activePollutant) {
			return null
		}
		
		let geometries = {
			"CO": () => new THREE.ConeGeometry( .78, 1.2, 5 ),
			"TSP": () => new THREE.CylinderGeometry(.7, .5, 1, 5 ),
			"SO2": () => new THREE.CylinderGeometry(.3, .3, 1.6, 5 ),
			"BC": () => new THREE.IcosahedronGeometry(.8, 0),
			"NMVOC": () => new THREE.OctahedronGeometry(.8),
			"PM10": () => new THREE.DodecahedronGeometry(.8),
			"PM2.5": () => new THREE.DodecahedronGeometry(.4),
			"NH3": () => new THREE.TetrahedronGeometry(.8),
			"NOx": () => new THREE.TorusGeometry( .6, .3, 4, 8 )
		}
		
		
		
		return geometries[activePollutant]()
		
		// return	new THREE.DodecahedronGeometry(.8)
	}
	const cubeMaterial = new THREE.MeshNormalMaterial();
	

	
	$: {
		activePollutant
		
		if(isThereAMesh()) {
			removeMesh()
		}
		if(cubeGeometry() != null) {
			addMesh()
		}
		
	}
	
	function isThereAMesh() {
		return mesh != null
	}
	
	function removeMesh() {
		scene.remove(mesh)
		mesh.geometry.dispose()
		mesh.material.dispose()
		mesh = null;
	}
	
	function addMesh() {
		mesh = new THREE.Mesh( cubeGeometry(), cubeMaterial );
		scene.add(mesh)
	}
	
	const renderer = new THREE.WebGLRenderer( { antialias: true, alpha: true} );
	renderer.setPixelRatio( window.devicePixelRatio );
	
	let camera = null
	
	$:{
		if(size.h > 0) {
			camera = new THREE.OrthographicCamera(-1, 1, size.h / size.w, size.h / size.w * -1, 0, 10)
			camera.position.z = 1
			camera.position.x = 0
		}
	}


	$: renderer.setSize( size.w, size.h );
	
	onMount(() => {
		renderer.setAnimationLoop( animation );
		pollutantGraphicElement.appendChild( renderer.domElement );
	})
	
	$: isAnyPollutantActive = activePollutant != null
	
	// animation
	
	function animation( time ) {
		if(camera != null) {
			renderer.render( scene, camera );
			if(mesh != null) {
				// console.log(mesh)
				// mesh.rotation.x = time / 2000
				mesh.rotation.y = time / 1400
				mesh.rotation.z = time / 2400
			}
		}
	
	}

	$: colorScaled = colorScale(activePollutant)
	$: color = chroma(colorScaled)
	$: textColor = color.luminance(.21).desaturate(0.9)
	$: textColorMuted = color.luminance(.35).desaturate(1.5)
	$: backgroundColor = color.luminance(.8)
	$: shadowColor = color.luminance(.1).desaturate(1.5)
	
	$: pollutantBaseYear = 2
	
	$: valuesArray = $store.pollutants.find(([name, _]) => name == activePollutant)
	$: values = valuesArray ? valuesArray[1] : []
	$: baseYear = $store.getFirstYear(values)
	$: baseValue = $store.getBaseValue(values)
	
	$: currentValue = () => {
		let val = values.find(([year, _]) => year == currentYear)
		
		return val ? val[1] : null
	}
	
	$: maxYear = $store.getMaxYear()
	$: maxYearValue = () => {
		let val = values.find(([year, _]) => year == maxYear)
		
		return val ? val[1] : null
	}
	
	$: percentageChange = $store.niceNumbers((maxYearValue() / baseValue * 100).toFixed(0))
	$: currentPercentageChange = $store.niceNumbers((currentValue() / baseValue * 100).toFixed(0))
	$: baseValueNiced = baseValue ? $store.niceNumbers(baseValue.toFixed(0)) : baseValue
	$: maxValueNiced = maxYearValue() ? $store.niceNumbers(maxYearValue().toFixed(0)) : maxYearValue()
	$: currentValueNiced = currentValue() ? $store.niceNumbers(currentValue().toFixed(0)) : currentValue()
</script>

<style>
.wrapper {
	width: 30%;
	/* max-width: 20rem; */
	z-index: 1;
	display: flex;
	flex-direction: column;
	background: var(--colorBackground);
	border-left: 2px solid var(--colorBorder);
}

.sticky-wrapper {
	position: sticky;
	top: 6rem;
	padding: 2rem .5rem 1rem 1rem;
	max-height: calc(100vh - 6rem);
	box-sizing: border-box;
	overflow-y: auto;
}
.pollutant-graphic {
	height: 100%;
	width: 100%;
	/* padding: .5rem; */
	mix-blend-mode: color-burn;
	filter: brightness(1) ;
}

.graphic-wrapper {
	position: relative;
	left: -.2rem;
	width: 10rem;
	height: 10rem;
	box-sizing: border-box;
	padding: .25rem;
	background: var(--color);
	border-radius: 50%;
}
.pollutant-graphic :global(canvas) {
	filter: drop-shadow(0px 0px 5px var(--color-shadow));
}

.title {
	display: flex;
	align-items: center;
	/* justify-content: space-between; */
	gap: .5rem;
}
.pollutant-name .nickname {
	font-size: 1.2rem;
	font-weight: 600;
	letter-spacing: .1rem;
	/* color: var(--colorPrimary); */
	color: var(--color-text);
	/* font-feature-settings: "smcp"; */
	/* font-variant: all-small-caps; */
}


.pollutant-name .fullname {
	font-size: .9rem;
	color: var(--color-text-muted);
}
.pollutant-name {
	display: flex;
	flex-direction: column;
}

.text p {
	font-size: 1rem;
	line-height: 1.5;
	max-width: 27rem;
}

.hide {
	display: none;
}

.no-active-pollutant {
	text-align: center;
	padding: 2rem 0;
	color: var(--colorTextMuted);
}

.notice {
	font-style: italic;
}


.legend {
	max-width: 17rem;
	display: block;
	margin: 4rem 0;
}
.data-info {
	font-variant-numeric: tabular-nums;
}
.data-info .value {
	display: flex;
	flex-direction: column;
}
.data-info .year {
	color: var(--colorPrimary);
	/* font-style: italic; */
}
.data-info .amount-set {
	width: 13rem;
	display: flex;
	justify-content: space-between;
	transition: .1s opacity ease;
	gap: .5rem;
}
.data-info .title {
	font-variant-caps: all-small-caps;
	letter-spacing: .05rem;
	color: var(--colorTextMuted);
	margin: 1rem 0 .5rem;
}

.data-info .percentage {
	width: 4rem;
	text-align: right;
}

.data-info .amount {
	font-weight: 600;
	text-align: right;
	flex: 10 1;
}
.hide-opacity {
	opacity: .3;
	/* color: var(--colorTextMuted); */
}

.text .source {
	font-size: .9rem;
	color: var(--colorTextMuted);
}

</style>

<div class="wrapper" style="
	--color: {backgroundColor};
	--color-shadow: {shadowColor};
	--color-text: {textColor};
	--color-text-muted: {textColorMuted};
">

<div class="sticky-wrapper">
	
	<div 
	class="no-active-pollutant"
	class:hide={isAnyPollutantActive}>
		<span class="notice">
			Choose a pollutant in the graph to get more information.
		</span>
		
		<svg class="legend" viewBox="0 0 2006 964" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
			<title>Group 2</title>
			<defs>
				<path d="M482,964 C748.201249,964 964,748.201249 964,482 C964,215.798751 748.201249,0 482,0 C215.798751,0 0,215.798751 0,482 C0,748.201249 215.798751,964 482,964 Z" id="path-1"></path>
				<mask id="mask-2" maskContentUnits="userSpaceOnUse" maskUnits="objectBoundingBox" x="0" y="0" width="964" height="964" fill="white">
					<use xlink:href="#path-1"></use>
				</mask>
			</defs>
			<g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
				<g id="Artboard" transform="translate(-1282.000000, -586.000000)">
					<g id="Group-2" transform="translate(1282.000000, 586.000000)">
						<circle id="Oval" stroke="#ABC4BD" stroke-width="16" fill-opacity="0.240821678" fill="#87A69D" cx="482" cy="482" r="301"></circle>
						<use id="Oval-Copy" stroke="#ABC4BD" mask="url(#mask-2)" stroke-width="14" stroke-dasharray="37,49" xlink:href="#path-1"></use>
						<text id="Pollutant" font-family="TheMix-SemiBold, TheMix" font-size="74" font-weight="500" letter-spacing="12.663636" fill="#87A69D">
							<tspan x="233.433276" y="511.5">POLLUTANT</tspan>
						</text>
						<text id="Selected-year-pollut" font-family="TheMix-BoldItalic, TheMix" font-size="95" font-style="italic" font-weight="bold" fill="#87A69D">
							<tspan x="1091" y="518.127025">Selected year </tspan>
							<tspan x="1091" y="641.127025" font-family="TheMix-Plain, TheMix" font-weight="normal">pollution amount</tspan>
						</text>
						<text id="Base-year-pollution" font-family="TheMix-BoldItalic, TheMix" font-size="95" font-style="italic" font-weight="bold" fill="#87A69D">
							<tspan x="1091" y="126.247025">Base year </tspan>
							<tspan x="1091" y="249.247025" font-family="TheMix-Plain, TheMix" font-weight="normal">pollution amount</tspan>
						</text>
						<text id="Percentage-differenc" font-family="TheMix-Plain, TheMix" font-size="95" font-weight="normal" fill="#87A69D">
							<tspan x="1091" y="899.007025">Percentage difference</tspan>
						</text>
						<text id="52-%" font-family="TheMix-Bold, TheMix" font-size="59" font-weight="bold" letter-spacing="2.68181818" fill="#87A69D">
							<tspan x="416.5" y="884">52 %</tspan>
						</text>
						<g id="Group" transform="translate(933.500000, 92.247025) scale(-1, 1) translate(-933.500000, -92.247025) translate(825.000000, 61.747025)" stroke="#ABC4BD" stroke-width="7">
							<line x1="0" y1="30.5" x2="217" y2="30.5" id="Path-45"></line>
							<polyline id="Path-46" points="171 0 217 30.5 171 61"></polyline>
						</g>
						<g id="Group-Copy-2" transform="translate(811.500000, 864.500000) scale(-1, 1) translate(-811.500000, -864.500000) translate(581.000000, 834.000000)" stroke="#ABC4BD" stroke-width="7">
							<line x1="0" y1="30.5" x2="461" y2="30.5" id="Path-45"></line>
							<polyline id="Path-46" points="415 0 461 30.5 415 61"></polyline>
						</g>
						<g id="Group-Copy" transform="translate(941.000000, 487.000000) scale(-1, 1) translate(-941.000000, -487.000000) translate(840.000000, 456.500000)" stroke="#ABC4BD" stroke-width="7">
							<line x1="0" y1="30.5" x2="202" y2="30.5" id="Path-45"></line>
							<polyline id="Path-46" points="156 0 202 30.5 156 61"></polyline>
						</g>
					</g>
				</g>
			</g>
		</svg>
	</div>
	<div 
		class="active-pollutant"
		class:hide={!isAnyPollutantActive}
	>
		<div class="title">
			<div class="graphic-wrapper">
				
				<div class="pollutant-graphic" bind:this={pollutantGraphicElement} bind:clientWidth={size.w} bind:clientHeight={size.h} title="Artistic representation of a particle" />
			</div>
			
			<div class="pollutant-name">
				<span class="nickname">
					{activePollutant}
				</span>
				<span class="fullname">
					{pollutantTitles[activePollutant]}
				</span>
			</div>
	
		</div>
		{#if isAnyPollutantActive}
			<div class="text">
				{#each pollutantTexts[activePollutant] as paragraph}
					<p>
						{paragraph}
					</p>
				{/each}
				
				<span class="source">
					Source <a href={pollutantTextSources[activePollutant]} target="_blank">{pollutantTextSources[activePollutant].slice(8, 31)} … {pollutantTextSources[activePollutant].slice(-10)}</a>
				</span>
			</div>
		{/if}
		
		
		
		<div class="data-info">
			<span class="title">Total Change</span>
			<span class="value" >
				<span class="amount-set">
					<span class="year">
						{baseYear}
					</span>
					<span class="amount">
						{baseValueNiced} kt
					</span>
					<span class="percentage">
						100 %
					</span>
				</span>
				
				<span class="amount-set" class:hide-opacity={currentYear == baseYear || currentYear == maxYear}>
					<span class="year">
						{currentYear}
					</span>
					<span class="amount">
						{currentValueNiced} kt
					</span>
					<span class="percentage">
						{currentPercentageChange} %
					</span>
				</span>
				
				<span class="amount-set">
					<span class="year">
						{maxYear}
					</span>
					<span class="amount">
						{maxValueNiced} kt
					</span>
					<span class="percentage">
						{percentageChange} %
					</span>
				</span>
			</span>
		</div>
		
	</div>
</div>

</div>